parameters:
  - name: scheduleDisplayName
    type: string
  - name: scheduleCron
    type: string
  - name: triggerOnChange
    type: boolean
    default: false
  - name: jobName
    type: string
  - name: jobDisplayName
    type: string
  - name: testAzureSubscription
    type: string
  - name: newDir
    type: string
  - name: testsFolder
    type: string
  - name: makeTarget
    type: string

${{ if eq(parameters.triggerOnChange, true) }}:
  trigger:
    branches:
      include:
      - main

${{ if ne(parameters.triggerOnChange, true) }}:
  trigger: none  # Disable automatic CI triggers

schedules:
- cron: ${{ parameters.scheduleCron }}
  displayName: ${{ parameters.scheduleDisplayName }}
  branches:
    include:
    - main
  always: true  # Run even if there are no code changes

jobs:
- template: test-job-template.yml
  parameters:
    jobName: ${{ parameters.jobName }}
    jobDisplayName: ${{ parameters.jobDisplayName }}
    testAzureSubscription: ${{ parameters.testAzureSubscription }}
    newDir: ${{ parameters.newDir }}
    testsFolder: ${{ parameters.testsFolder }}
    makeTarget: ${{ parameters.makeTarget }}
